[package]
name = "rust-design-pattern-guru"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [ 
    "factory-dialog-rendering", 
    "factory-maze-game", 
    "prototype-buildin-clone", 
    "singleton-lazy", 
    "singleton-mutex",
    "singleton-safe-singleton",
]

